VINCENT-ARCHIVE/Vincent-Server

src/main/java/com/vincent/domain/bookmark/controller/BookmarkController.java
src/main/java/com/vincent/domain/bookmark/controller/dto/BookmarkResponseDto.java
src/main/java/com/vincent/domain/bookmark/converter/BookmarkConverter.java
src/main/java/com/vincent/domain/bookmark/repository/BookmarkRepository.java
src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java
src/main/java/com/vincent/domain/socket/entity/Socket.java
src/test/java/com/vincent/domain/bookmark/controller/BookmarkControllerTest.java
src/test/java/com/vincent/domain/bookmark/service/BookmarkServiceTest.java

> #21 
> 1. 소켓의 식별번호(이름) 추가
> 2. 북마크된 소켓의 정보 리스트 controller, service, repository, converter, dto 작성
> 3. 한 페이지 당 10개 리스트씩 보이도록 페이징 처리

Feat/21 찜한 콘센트 리스트 조회 api

---

src/main/java/com/vincent/domain/feedback/controller/FeedbackController.java
src/main/java/com/vincent/domain/feedback/controller/dto/FeedbackRequestDto.java
src/main/java/com/vincent/domain/feedback/entity/Feedback.java
src/main/java/com/vincent/domain/feedback/repository/FeedbackRepository.java
src/main/java/com/vincent/domain/feedback/service/FeedbackService.java
src/test/java/com/vincent/domain/bookmark/controller/FeedbackControllerTest.java
src/test/java/com/vincent/domain/bookmark/service/FeedbackServiceTest.java

> #25
> 주요 기능 : 프론트에서 contents를 dto로 받아  memberId와 contents를 Bookmark 엔티티로 변환하여 save한다
> 테스트 코드 : contents는 @Valid를 통해 max = 300을 검증했으므로, 성공하는 경우와 멤버가 존재하지 않는 경우만 테스트 함

Feat/25 피드백 생성하기 api

---

src/main/java/com/vincent/domain/bookmark/controller/BookmarkController.java
src/main/java/com/vincent/domain/socket/controller/SocketController.java
src/main/java/com/vincent/domain/socket/controller/dto/SocketResponseDto.java
src/main/java/com/vincent/domain/socket/converter/SocketConverter.java
src/main/java/com/vincent/domain/socket/service/SocketService.java
src/test/java/com/vincent/domain/bookmark/controller/SocketControllerTest.java
src/test/java/com/vincent/domain/bookmark/service/SocketServiceTest.java

> #38 
1. socketId와 memberId를 각각 socketService와 bookmarkService에 전달하여 소켓정보, 북마크 여부를 받아와 SocketConverter에 전달해서, 소켓정보와 북마크 정보를 합친 ResponseDto를 프론트에 전달하도록 함
2. 기존의 북마크 여부 조회 api(BookmarkController에 있던 api)는 주석처리함
3. 개별 콘센트 조회 컨트롤러 테스트의 예외 상황은 테스트 하지 못함. 나머지 컨트롤러 성공 테스트, 서비스의 성공/예외 테스트는 정상적으로 실행됨

Feat/38 개별 콘센트 조회 api

---

src/main/java/com/vincent/apipayload/status/ErrorStatus.java
src/main/java/com/vincent/domain/building/controller/BuildingController.java
src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
src/main/java/com/vincent/domain/building/entity/Space.java
src/main/java/com/vincent/domain/building/repository/FloorRepository.java
src/main/java/com/vincent/domain/building/repository/SpaceRepository.java
src/main/java/com/vincent/domain/building/service/BuildingService.java
src/test/java/com/vincent/domain/bookmark/controller/BuildingControllerTest.java
src/test/java/com/vincent/domain/bookmark/service/BuildingServiceTest.java

> #50 
건물 Id와 층을 RequestParam으로 받아서 해당 건물의 이름, 총 층 수, 현재 층, 공간의 정보 리스트들이 조회되도록 했습니다.
Floor엔티티에 isSocketExist 필드를 추가했습니다
해당 필드를 추가하지않고 소켓 존재 여부를 BuildingSerivce에서 조회할 수 있지만, 그렇게 되면
BuilidingConverter의 toSpaceInfoResponse메서드의 파라미터가 space 엔티티와 Boolean형의 isSocketExist가 되고,
그러면 BuilidingConverter의 toFloorInfoListResponse메서드에서 map함수를 쓰지 못하게 됩니다.
따라서 Floor엔티티에 isSocketExist 필드를 추가했는데 다른 의견 주시면 바꾸겠습니다
controller테스트 코드는 완성했지만 service테스트 코드는 모두 작성하지못했습니다. 나머지 api를 만들고 추가하겠습니다

Feat/50 층 조회 api

---

src/main/resources/application.yml

> #76 
1. 서버가 터졌을 때 아래와 같은 오류가 나서 우선 pool-size를 50으로 늘려줬습니다. 아마 서버에 누가 악의적으로 계속 트래픽을 보내서 과부하가 걸리게 했던거 같은데 제가 따로 Nginx 설정을 안해둬서 정확한 원인은 파악하지 못했습니다.
2. 로깅을 위해 서버에 Nginx 설치
> springboot    | [2024-08-24 22:06:39:225711454]  WARN  1 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=2m3s344ms900µs621ns).

[Bug/76] Hikaripool Thread starvation 오류

---

.gitignore
src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java
src/main/java/com/vincent/domain/bookmark/service/data/BookmarkDataService.java
src/main/java/com/vincent/domain/building/repository/FloorRepository.java
src/main/java/com/vincent/domain/building/service/data/BuildingDataService.java
src/main/java/com/vincent/domain/building/service/data/FloorDataService.java
src/main/java/com/vincent/domain/building/service/data/SpaceDataService.java
src/main/java/com/vincent/domain/feedback/service/data/FeedbackDataService.java
src/main/java/com/vincent/domain/member/service/data/MemberDataService.java
src/main/java/com/vincent/domain/socket/service/data/SocketDataService.java

> #80 
1. Data 계층 생성
> 기존 방식이 controller -> service -> repository 였는데 service 계층에서 repository에 접근해서 데이터 검증 및 비지니스 로직을 모두 처리헤고 되면서 코드의 복잡도가 증가해서 이러한 문제를 해결하기 위해 가운데 data 계층을 새로 생성함
> 변경된 방식은 controler -> serivce -> data -> repository  순서로 service 계층에서는 비지니스 로직에만 집중하고, data 계층에서 repository에 접근해서 데이터를 가져오고 검증하는 역할을 수행하도록 했다. 
일단 최대한 data 계층에 넣을 수 있는 건 다 넣어봤는데 몇 개 빼먹은 건 있을 수 있습니다...😅😅

[Refactor/80] Service 코드 수정

---

src/main/java/com/vincent/config/redis/repository/RefreshTokenRepository.java
src/main/java/com/vincent/config/redis/service/RedisService.java
src/main/java/com/vincent/domain/member/service/MemberService.java
src/main/java/com/vincent/domain/member/service/data/MemberDataService.java
src/test/java/com/vincent/config/redis/service/RedisServiceTest.java
src/test/java/com/vincent/domain/member/service/MemberServiceTest.java
src/test/java/com/vincent/domain/member/service/data/MemberDataServiceTest.java

> #83 
1. MeberService에서 MemberRepository에 직접 접근해서 데이터를 가져오지 않고 MemberDataService를 통해서 데이터에 접근할 수 있도록 수정.
2. MemberService에서 순수하게 비지니스 로직에만 집중할 수 있게, 예외 처리를 모드 MemberDataService, RedisService에서 할 수 있게 수정.
3. 수정된 코드에 맞게 테스트 코드 재작성 (MemberService, MeberDataService, RedisService)
- 기존의 MemberService가 비즈니스 로직과 데이터 접근 로직을 모두 포함하고 있었기 때문에, 테스트 코드 작성 시 여러 가지 의존성을 관리해야 했지만 이제 MemberService와 MemberDataService로 역할이 명확하게 분리됨에 따라, 각각의 단위 테스트를 더 쉽게 작성할 수 있게 됐다.
-  MemberService와 MemberDataService가 각각 명확한 책임을 가지게 되면서, 코드가 더 이해하기 쉽고 유지보수하기 쉬워졌다.

[Refactor/83] MemberService 코드 수정

---

src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
src/main/java/com/vincent/domain/building/repository/BuildingRepository.java
src/main/java/com/vincent/domain/building/repository/FloorRepository.java
src/main/java/com/vincent/domain/building/repository/SpaceRepository.java
src/main/java/com/vincent/domain/building/repository/customBuilding/CustomBuildingRepository.java
src/main/java/com/vincent/domain/building/repository/custombuilding/CustomBuildingRepository.java
src/main/java/com/vincent/domain/building/repository/custombuilding/CustomBuildingRepositoryImpl.java
src/main/java/com/vincent/domain/building/repository/customfloor/CustomFloorRepository.java
src/main/java/com/vincent/domain/building/repository/customfloor/CustomFloorRepositoryImpl.java
src/main/java/com/vincent/domain/building/repository/customspace/CustomSpaceRepository.java
src/main/java/com/vincent/domain/building/repository/customspace/CustomSpaceRepositoryImpl.java
src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java

> #82 
> Buiding, Floor, Space 레포지토리를 spring data jpa와 아닌 것으로 분리함
jpql를 사용하는 쿼리는 Custom(엔티티명)Repository 라는 인터페이스를 도입하여 impl파일에서 구현한 후, 기존의 레포지토리에서 Custom(엔티티명)Repository 인터페이스를 상속하여 사용하도록 변경하였음
Space, Floor 레포지토리는 기존에 SpaceInfoProjection, FloorInfoProjection 이라는 인터페이스로 반환되었음. Dto로 바로 반환할 수 없었기 때문에. 
그러나 jpql쿼리에서는 결과를 자동으로 Projection 인터페이스에 매핑할 수 없기때문에 다시 dto로 변경함.
FloorInfoProjection 클래스에서 생성자의 두 번째 파라미터가 Integer floors인데, 이걸 반환하는 jpql 쿼리는 Count를 사용하고 count는 long을 반환하기 때문에 타입을 변경하였음.

Refactor/82 Repository 분리

---

src/main/java/com/vincent/domain/bookmark/repository/BookmarkRepository.java
src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java
src/test/java/com/vincent/domain/bookmark/service/BookmarkServiceTest.java
src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java

> #113
> 기존의 바로 delete함수에서 bookmark엔티티를 빌더패턴으로 생성해서 제거하는 방식에서, BookmarkRepository에 findByMemberAndSocket을 추가하여 bookmark객체를 생성한 후 해당 객체를 delete 함수에 적용하는 방식으로 바꾸었습니다

[Hotfix/113] :hammer: BookmarkService -> delete 함수 수정

---

src/main/java/com/vincent/domain/feedback/controller/FeedbackController.java
src/main/java/com/vincent/domain/feedback/entity/Feedback.java

> #115 
> Feedback 엔티티 : @EntityListeners(AuditingEntityListener.class) 추가 -> createdAt 생성되도록 수정
> FeedbackController : @Parameter(name = "contents", description = "내용은 최대 300자까지 가능")제거 -> request 중복 제거

[Fix/115] :hammer: 피드백 생성 시 생성시간 설정, request 중복 제거

---

src/main/java/com/vincent/apipayload/status/ErrorStatus.java
src/main/java/com/vincent/domain/bookmark/repository/BookmarkRepository.java
src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java
src/main/java/com/vincent/domain/bookmark/service/data/BookmarkDataService.java
src/test/java/com/vincent/domain/bookmark/service/BookmarkServiceTest.java
src/test/java/com/vincent/domain/bookmark/service/data/BookmarkDataServiceTest.java

> #113 
> 기존의 delete함수에서 bookmark엔티티를 바로 빌더패턴으로 생성해서 제거하는 방식에서, BookmarkRepository에 findByMemberAndSocket을 추가하여 bookmark객체를 생성한 후 해당 객체를 delete 함수에 적용하는 방식으로 바꾸었습니다

[Fix/113] :hammer: 북마크 취소 api 수정

---

src/main/java/com/vincent/domain/building/controller/BuildingController.java
src/main/java/com/vincent/domain/building/repository/custombuilding/CustomBuildingRepositoryImpl.java

> #130
1. 빌딩을 조회하면 keyword에 빈 문자열이 들어가면서 모든 건물을 조회하게 되는 오류가 있었습니다.
``` Java
String jpql = "SELECT b FROM Building b WHERE b.name LIKE CONCAT('%', :keyword, '%') "
+ "ORDER BY CASE "
+ "WHEN b.name = :keyword THEN 0 "
+ "WHEN b.name LIKE CONCAT(:keyword, '%') THEN 1 "
+ "WHEN b.name LIKE CONCAT('%', :keyword, '%') THEN 2 "
+ "WHEN b.name LIKE CONCAT('%', :keyword) THEN 3 "
+ "ELSE 4 END";
```
그래서 빈 문자열이 들어오면 검색을 하지 않도록 하는 로직을 추가했습니다.
```
if (keyword == null || keyword.trim().isEmpty()) {
return new PageImpl<>(Collections.emptyList(), pageRequest, 0);
}
```

:hammer: 빌딩 검색 api 수정

---

src/main/java/com/vincent/domain/building/controller/BuildingController.java
src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
src/main/java/com/vincent/domain/building/repository/FloorRepository.java
src/main/java/com/vincent/domain/building/repository/customfloor/CustomFloorRepository.java
src/main/java/com/vincent/domain/building/repository/customfloor/CustomFloorRepositoryImpl.java
src/main/java/com/vincent/domain/building/service/BuildingService.java
src/main/java/com/vincent/domain/building/service/data/FloorDataService.java
src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
src/test/java/com/vincent/domain/building/service/data/FloorDataServiceTest.java

> #123 
1. 건물 정보 조회api에 소켓이 있는 층들의 리스트 필드 추가
2. 층 조회 api에 해당 필드 잘못 추가한 후 수정하여 건물 정보 조회 api로 제대로 추가 하였음

[Fix/123] 건물 정보 조회api 수정

---

src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
src/main/java/com/vincent/domain/socket/controller/dto/SocketResponseDto.java

> #142 
> 층 콘센트 조회 시  @jsonProperty를 이용하여 x축 y축을 소문자로 설정하였고, 층 조회 api와 층 콘센트 조회 api의 응답값이 해당 어노테이션을 사용한 후 필드 순서가 달라져서 @JsonPropertyOrder를 이용해 순서를 고정함

[Fix/142] :hammer: 층 콘센트 조회 @jsonProperty 추가, @jsonPropertyOrder로 순서 고정

---

src/main/java/com/vincent/domain/socket/controller/SocketController.java
src/main/java/com/vincent/domain/socket/controller/dto/SocketResponseDto.java
src/main/java/com/vincent/domain/socket/converter/SocketConverter.java
src/main/java/com/vincent/domain/socket/repository/SocketRepository.java
src/main/java/com/vincent/domain/socket/repository/customsocket/CustomSocketRepository.java
src/main/java/com/vincent/domain/socket/repository/customsocket/CustomSocketRepositoryImpl.java
src/main/java/com/vincent/domain/socket/service/SocketService.java
src/main/java/com/vincent/domain/socket/service/data/SocketDataService.java
src/test/java/com/vincent/domain/socket/controller/SocketControllerTest.java
src/test/java/com/vincent/domain/socket/service/SocketServiceTest.java
src/test/java/com/vincent/domain/socket/service/data/SocketDataServiceTest.java

> #170 
소켓 조회 api의 responseDto에 buildingId와 level필드를 추가
페이징된 북마크 리스트에서, 북마크된 소켓의 id를 이용하여 해당 소켓과 연결된 floor, building엔티티의 필드를 쿼리로 가져와서 다시 ResponseDto에 넣는 과정이 복잡했음
소켓의 id를 RequestParam으로 받으면 빌딩id와 level을 리턴하는 새로운 api를 만듦
socketDataservice : 인자로 받은 소켓id로 먼저 소켓의 존재 여부를 확인하고 소켓이 있으면 
socket, space, floor, building 엔티티를 삼중 join 하여 두 필드를 리턴하는 쿼리에 id를 넘겼고 소켓이 없으면 에러메시지를 출력하도록 했음
1. customSocketRepositoryImpl : jpql문 중 
이 부분에서 '(' expected, got '.' 오류 발생
inner 클래스를 new 키워드와 함께 JPQL에서 사용할 때 나타나는 문제이며 SocketResponseDto.SocketPlace를 별도의 public 클래스로 정의하거나, 내부 클래스의 정적(static) 선언을 확인해 보아야 한다는데 이미 static 선언이 되어있음
그리고 빨간 줄을 무시하고 실행해도 api가 작동이 잘 되기에 무시했음

🔨 Fix/170 소켓 장소 조회 api

---

src/main/java/com/vincent/logging/LoggingFilter.java
src/main/java/com/vincent/logs/LogService.java
src/main/java/com/vincent/logs/entity/ApiLogs.java

> #173
로그 데이터베이스에 스웨거에 대한 요청도 저장되서 실제 사용자 요청을 파악하기 어려웠습니다. 그래서 스웨거에 대한 요청은 로깅하지 않게 개선했습니다.
또한 데이터베이스에 로그 메세지를 그대로 저장해서 가독성이 떨어져서, 이를 분리해서 저장되게 했습니다.

:hammer: 로깅 수정

---

src/test/java/com/vincent/config/redis/service/RedisServiceTest.java
src/test/java/com/vincent/config/redis/service/TestRedisService.java
src/test/java/com/vincent/config/redis/service/TestRedisTemplate.java
src/test/java/com/vincent/config/redis/service/TestRefreshTokenRepository.java
src/test/java/com/vincent/domain/member/TestJwtProvider.java
src/test/java/com/vincent/domain/member/TestMemberDataService.java
src/test/java/com/vincent/domain/member/TestMemberRepository.java
src/test/java/com/vincent/domain/member/service/MemberServiceTest.java
src/test/java/com/vincent/domain/member/service/data/MemberDataServiceTest.java
src/test/java/com/vincent/e2e/domain/MemberControllerTest.java

> #177 
멤버쪽 테스트 코드에서 모킹을 제거 했습니다. 
기존 코드는 의존성들을 Mockito로 모킹하여 테스트 했는데, 모킹의 문제는 단순히 메서드 호출에 대한 예상 결과를 반환하기 때문에 내부 로직이나 데이터베이스 쿼리의 실제 동작과 다를 수 있었습니다.
이를 해결하기 위해, 테스트에 필요한 의존성들을 직접 구현하여 테스트 할 수 있게 변경했습니다.
이번에 모킹을 제거해서 테스트 코드를 작성하는 것이 처음이어서 틀린 부분이 있을 수 있습니다..😅😅

:recycle: 멤버 테스트 코드 모킹 제거

---

src/main/java/com/vincent/domain/socket/repository/customsocket/CustomSocketRepository.java
src/main/java/com/vincent/domain/socket/repository/customsocket/CustomSocketRepositoryImpl.java
src/main/java/com/vincent/domain/socket/service/SocketService.java
src/main/java/com/vincent/domain/socket/service/data/SocketDataService.java
src/test/java/com/vincent/domain/building/TestBuildingRepository.java
src/test/java/com/vincent/domain/building/TestFloorRepository.java
src/test/java/com/vincent/domain/building/TestSpaceRepository.java
src/test/java/com/vincent/domain/socket/TestSocketRepository.java
src/test/java/com/vincent/domain/socket/service/SocketServiceTest.java
src/test/java/com/vincent/domain/socket/service/data/SocketDataServiceTest.java

> #176  
- **데이터베이스 호출 횟수**
- `buildingDataService.findById(buildingId)` → 1번 호출
- `floorDataService.findByBuildingAndLevel(building, level)` → 1번 호출
- `spaceDataService.findAllByFloor(floor)` → 1번 호출
- 각 `space`에 대해 `socketDataService.findAllBySpace(space)` 호출 → **`space` 개수만큼 반복 호출**
- 총 데이터베이스 호출 횟수는 **N+3번** (N: `space`의 개수).
- **단점**
- **N+1 문제 발생**: `space` 개수만큼 추가로 데이터베이스 쿼리가 발생. -> 조회 속도 느림
- 데이터베이스 호출 횟수가 많아질수록 조회 속도가 느려짐.
- > building, floor, space, socket을 4중 join하여 파라미터인 buildingId, Level에 해당하는 소켓 리스트만 리턴하도록 함
- **데이터베이스 호출 횟수**
- JPQL 쿼리가 한 번 호출되며, 단일 쿼리로 모든 데이터를 가져옴.
- 총 데이터베이스 호출 횟수는 **1번**.
- 
- **장점**
- 단일 쿼리로 필요한 데이터를 모두 가져오므로 **N+1 문제 해결**.
- 데이터베이스가 연관 관계를 따라 데이터를 효율적으로 조회하므로 속도가 더 빠름.
- findAllBySpace(Space space)
특정 Space에 연결된 모든 Socket을 반환.
Socket 리스트에서 space와 연결된 …

[Fix/176] 층 콘센트 조회 성능 개선 & 소켓 테스트 코드 모킹 제거

---

src/main/java/com/vincent/domain/socket/converter/SocketConverter.java
src/main/java/com/vincent/domain/socket/repository/SocketRepository.java
src/main/java/com/vincent/domain/socket/repository/customsocket/CustomSocketRepository.java
src/main/java/com/vincent/domain/socket/repository/customsocket/CustomSocketRepositoryImpl.java
src/main/java/com/vincent/domain/socket/service/SocketService.java
src/main/java/com/vincent/domain/socket/service/data/SocketDataService.java
src/test/java/com/vincent/domain/socket/TestSocketRepository.java
src/test/java/com/vincent/domain/socket/controller/SocketControllerTest.java
src/test/java/com/vincent/domain/socket/service/SocketServiceTest.java
src/test/java/com/vincent/domain/socket/service/data/SocketDataServiceTest.java

> #186
1. Socket Service 테스트 코드에서 모킹 제거
2. Socket API에서 콘센트 위치를 조회하는 API 수정
- 기존 API는 비즈니스 로직이 JPQL 쿼리문에 포함되어 있어 쿼리 단계에서 필요한 데이터만 조회하는 방식이었다
- 즉, 비지니스 로직이 변경된다면, 코드 뿐만 아니라 쿼리문까지 변경해야 하고, 테스트 코드 작성이 어렵다는 단점이 있다.
- 이를 모든 연관 데이터를 한꺼번에 조회한 후, 코드에서 필요한 데이터를 추출하도록 수정
- 이렇게 함으로써, 나중에 반환해야 되는 데이터가 변경되거나, 비지니스 로직이 변경되도 쿼리문 수정은 하지 않고, 코드만 수정할 수 있게 됐다.
- CustomSocketRepository
``` java
String jpql = "SELECT new com.vincent.domain.socket.controller.dto.SocketResponseDto$SocketPlace("
+ "building.id, "
+ "floor.level ) "
+ "FROM Socket socket "
+ "JOIN socket.space space "
+ "JOIN space.floor floor "
+ "JOIN floor.building building "
+ "WHERE socket.id = :socketId";
```
- SocketConverter
``` java
public static SocketResponseDto.SocketPlace toSocketPlace(SocketResponseDto.SocketPlace socketPlace) { …
```

[Refactor/186] Socket 테스트 코드 수정 및 로직 수정

---

src/main/java/com/vincent/logs/LogService.java

> #189
> MAU 계산 로직이 저번달이 아닌 현재달을 기준으로 계산을 하고 있어서 사용자 수가 0이 나오는 문제가 있었습니다. 그래서 지난달을 기준으로 로그를 수집해서 계산하도록 수정했습니다

[Fix/189] MAU 로직 수정

---

src/main/java/com/vincent/domain/building/service/data/BuildingDataService.java
src/test/java/com/vincent/domain/building/service/data/BuildingDataServiceTest.java

> #188
숭실융합연구원(위도 : 37.496560236205376, 경도 : 126.95609432415551)을 중심으로
<맨 위> 
주소(Address) : 서울 동작구 상도동 산 49-36
위도(Latitude) : 37.4987715461518 / 경도(Longitude) : 126.956743703345
<맨 왼쪽>
주소(Address) : 서울 동작구 상도로55길 16
위도(Latitude) : 37.4972940859693 / 경도(Longitude) : 126.955080615043
위도 차이 = 0.00221130994643
경도 차이 = 0.0010137091125
를 도출하여 범위 변수를 수정했습니다

:hammer: [FIx/188] 주변 건물 조회 범위 변수 확대

---

src/main/java/com/vincent/config/redis/service/RedisKeyExpirationListener.java
src/main/java/com/vincent/config/redis/service/RedisService.java
src/main/java/com/vincent/config/security/SecurityConfig.java
src/main/java/com/vincent/domain/iot/controller/IotController.java
src/main/java/com/vincent/domain/iot/entity/Iot.java
src/main/java/com/vincent/domain/iot/entity/enums/MotionStatus.java
src/main/java/com/vincent/domain/iot/service/IotService.java
src/test/java/com/vincent/config/redis/service/RedisServiceTest.java
src/test/java/com/vincent/domain/iot/service/IotServiceTest.java

> #203 
움직임 여부의 변수 명은 motionStatus, 사용 여부의 변수 명은 isUsing으로 각각 재설정
ScheduledExecutorService를 사용해 10분 후에 작업을 실행하도록 설정.
Redis TTL 만료 여부를 확인한 뒤 소켓 상태를 변경.
motionStatus == 1인 경우 소켓 상태를 바로 true로 설정.
motionStatus == 0인 경우 10분 후 상태를 false로 변경.
Redis 키의 TTL이 만료되었는지 확인하는 로직을 RedisService에 추가.

:hammer: iot가 전달한 값에 따라 1 -> 사용중, 0 -> 10분 후 사용 없음으로 변경하는 로직

---

src/main/java/com/vincent/domain/iot/entity/Iot.java
src/main/java/com/vincent/domain/iot/service/IotService.java

> #211 
- IoT 엔티티에서 상태 변경을 직접 관리하도록, `activate()`, `deactivate()`, `updateSocketStatus()` 추가
- 서비스 계층에서 도메인 객체의 메서드를 호출하는 방식으로 변경
``` java
iot.updateMotionStatus(MotionStatus.ACTIVE);
iot.getSocket().setIsUsing(true);
```
``` java
// IotService
iot.activate();
//Iot
public class Iot {
public void activate() {
this.motionStatus = MotionStatus.ACTIVE;
this.socket.setIsUsing(true);
}
}
```

:recycle: DDD 원칙 적용하여 IoT 상태 관리 로직 개선
