src/main/java/com/vincent/domain/bookmark/entity/Bookmark.java, src/main/java/com/vincent/domain/building/entity/Building.java, src/main/java/com/vincent/domain/feedback/entity/Feedback.java, src/main/java/com/vincent/domain/member/entity/Member.java, src/main/java/com/vincent/domain/member/entity/enums/Gender.java, src/main/java/com/vincent/domain/socket/entity/Socket.java
=> Feat/3 Entity 생성

src/main/java/com/vincent/apipayload/status/ErrorStatus.java, src/main/java/com/vincent/domain/bookmark/controller/BookmarkController.java, src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java, src/test/java/com/vincent/domain/bookmark/controller/BookmarkControllerTest.java, src/test/java/com/vincent/domain/bookmark/service/BookmarkServiceTest.java
> #13 
> controller, service 작성
> 테스트 코드 작성
=> Feat/13 콘센트 찜하기 취소 api

src/main/java/com/vincent/domain/bookmark/controller/BookmarkController.java, src/main/java/com/vincent/domain/bookmark/controller/dto/BookmarkResponseDto.java, src/main/java/com/vincent/domain/bookmark/converter/BookmarkConverter.java, src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java, src/main/resources/application.yml, src/test/java/com/vincent/domain/bookmark/controller/BookmarkControllerTest.java, src/test/java/com/vincent/domain/bookmark/service/BookmarkServiceTest.java
> #26 
> 멤버id와 소켓id를 통해 북마크 존재 여부를 조회하는 controller, service 작성, 테스트 코드 추가
=> Feat/26 북마크 여부 조회 기능

src/main/java/com/vincent/apipayload/status/ErrorStatus.java, src/main/java/com/vincent/domain/building/controller/BuildingController.java, src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java, src/main/java/com/vincent/domain/building/converter/BuildingConverter.java, src/main/java/com/vincent/domain/building/repository/BuildingRepository.java, src/main/java/com/vincent/domain/building/service/BuildingService.java, src/test/java/com/vincent/domain/bookmark/controller/BuildingControllerTest.java, src/test/java/com/vincent/domain/bookmark/service/BuildingServiceTest.java
> #29 
> buildingId를 pathVariable로 받아서 해당 id를 가진 빌딩 정보를 조회하는 controller, service 추가, 해당 테스트 코드 추가
=> Feat/29 건물 정보 조회 기능

src/main/java/com/vincent/apipayload/status/ErrorStatus.java, src/main/java/com/vincent/config/redis/RedisConfig.java, src/main/java/com/vincent/domain/bookmark/controller/BookmarkController.java, src/main/java/com/vincent/domain/bookmark/controller/dto/BookmarkResponseDto.java, src/main/java/com/vincent/domain/bookmark/converter/BookmarkConverter.java, src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java, src/main/java/com/vincent/domain/building/controller/BuildingController.java, src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java, src/main/java/com/vincent/domain/building/converter/BuildingConverter.java, src/main/java/com/vincent/domain/building/entity/Floor.java, src/main/java/com/vincent/domain/building/entity/Space.java, src/main/java/com/vincent/domain/building/service/BuildingService.java, src/main/java/com/vincent/domain/feedback/controller/FeedbackController.java, src/main/java/com/vincent/domain/feedback/controller/dto/FeedbackRequestDto.java, src/main/java/com/vincent/domain/feedback/service/FeedbackService.java, src/main/java/com/vincent/domain/member/controller/dto/MemberRequestDto.java, src/main/java/com/vincent/redis/entity/BlackList.java, src/test/java/com/vincent/domain/bookmark/controller/BookmarkControllerTest.java
> #36 
수정한 ERD에 맞게 엔티티 수정 및 오류가 발생했던 코드 주석 처리
=> Fix/36 엔티티 수정

build.gradle, src/main/java/com/vincent/config/aws/s3/S3Config.java, src/main/java/com/vincent/config/aws/s3/S3Service.java, src/main/java/com/vincent/config/redis/entity/BlackList.java, src/main/java/com/vincent/config/redis/entity/RefreshToken.java, src/main/java/com/vincent/config/redis/repository/RefreshTokenRepository.java, src/main/java/com/vincent/config/redis/service/RedisService.java, src/main/java/com/vincent/config/security/SecurityConfig.java, src/main/java/com/vincent/config/security/filter/BlackListFilter.java, src/main/java/com/vincent/config/security/filter/JwtFilter.java, src/main/java/com/vincent/config/security/handler/JwtAuthenticationEntryPoint.java, src/main/java/com/vincent/config/security/provider/JwtProvider.java, src/main/java/com/vincent/domain/building/controller/BuildingController.java, src/main/java/com/vincent/domain/building/controller/dto/BuildingRequestDto.java, src/main/java/com/vincent/domain/building/converter/BuildingConverter.java, src/main/java/com/vincent/domain/building/entity/Building.java, src/main/java/com/vincent/domain/building/service/BuildingService.java, src/main/java/com/vincent/domain/member/service/MemberService.java, src/main/java/com/vincent/exception/ExceptionAdvice.java, src/main/resources/application.yml, src/test/java/com/vincent/domain/bookmark/service/BuildingServiceTest.java, src/test/java/com/vincent/domain/member/service/MemberServiceTest.java
> #41 
이미지를 받으면 S3에서 업로드해서 url을 데이터베이스에 저장할 수 있게 만들었습니다.
유효하지 않은 위도와 경도를 입력으로 받으면 에러 응답을 반환합니다. 근데 응답 형태가 기존 형태랑은 달라서 나중에 수정을 해야할거 같습니다.
`Controller`에 대한 테스트 못했습니다.
=> :sparkles: 건물 등록 API

src/main/java/com/vincent/domain/bookmark/controller/dto/BookmarkResponseDto.java, src/main/java/com/vincent/domain/bookmark/converter/BookmarkConverter.java, src/test/java/com/vincent/domain/bookmark/controller/BookmarkControllerTest.java
> #48
> BookmarkConverter 에서 toBookmarkDetailResponse 부분 수정
> BookmarkResponseDto 에서 bookmarkDetail 부분 수정
> BookmarkController 테스트 코드는 오류 발생(해결x) swagger에는 빌딩 이름과 공간 이름 정상적으로 보임
=> Fix/48 찜한 북마크 조회하기 api의 ResponseDto, Converter 수정

src/main/java/com/vincent/apipayload/status/ErrorStatus.java, src/main/java/com/vincent/config/aws/s3/S3Service.java, src/test/java/com/vincent/aws/S3ServiceTest.java
> #54 
1. S3 이미지 업로드 테스트 코드 작성
2. AWS S3 버킷 생성
- 관련된 환경변수들은 Notion에 올려두겠습니다
=> :hammer: S3 재설정 및 테스트 코드 작성

src/main/java/com/vincent/apipayload/status/ErrorStatus.java, src/main/java/com/vincent/config/aws/s3/S3Service.java, src/main/java/com/vincent/domain/building/controller/BuildingController.java, src/main/java/com/vincent/domain/building/entity/Space.java, src/main/java/com/vincent/domain/building/repository/SpaceRepository.java, src/main/java/com/vincent/domain/building/service/BuildingService.java, src/test/java/com/vincent/domain/bookmark/controller/BuildingControllerTest.java, src/test/java/com/vincent/domain/bookmark/service/BuildingServiceTest.java
> #53 
1. s3 config : floor, space image directory 추가
2. 공간 등록 로직 추가(controller, service)
3. 테스트 코드
=> Feat/53 공간 등록 api

.gitignore, build.gradle, monitoring/docker-compose.yml, monitoring/prometheus.yml, src/main/java/com/vincent/config/security/SecurityConfig.java, src/main/resources/application.yml
> #57 
1. Spring Actuator와 프로메테우스 의존성 추가
2. docker-compose로 prometheus, grafana 구성
=> [Feat/57] 모니터링 시스템 구축

.gitignore, src/main/java/com/vincent/logging/LoggingFilter.java, src/main/java/com/vincent/logging/RequestLogInfo.java, src/main/java/com/vincent/logging/RequestWrapper.java, src/main/java/com/vincent/logging/ResponseLogInfo.java, src/main/java/com/vincent/logging/ResponseWrapper.java, src/main/resources/logback.xml
> #59 
1. logback.xml 파일 작성
- 모든 로그들을 기록
- 사용자 요청과 응답은 별도의 파일에 기록
- 로그 파일이 날짜별로 생성될 수 있게 설정
3. LoggingFilter 클래스 구현
- 사용자의 요청과 응답을 로그로 기록하기 위한 필터
- 토큰이 존재하면 토큰에서 사용자 ID를 추출해서 로그에 기록, 없으면 anonymous로 기록
=> [Feat/59] 로깅 설정

src/main/java/com/vincent/domain/building/controller/BuildingController.java, src/main/java/com/vincent/exception/ExceptionAdvice.java, src/main/java/com/vincent/logging/LoggingFilter.java, src/main/resources/application.yml, src/main/resources/logback.xml
> #64 
LoggingFilter에서 multipart/form-data 데이터를 처리하지 못해서 발생했습니다. 우선 필터에서 multipart/form-data 데이터를 처리하지 않고 skip 하도록 수정했습니다.
=> [Bug/64] 빌딩 등록 오류 수정

src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java, src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
=> [Hotfix/85] Long -> Integer로 수정

src/main/java/com/vincent/domain/building/repository/BuildingRepository.java
> #88 
> 테이블 명이 존재하지 않는다는 (Table 'vincent.Building' doesn't exist) jdbc 오류 발생 -> 테이블의 첫 글자의 대문자를 소문자로 변경
=> [Hotfix/88] Repository의 네이티브 쿼리 테이블 명 변경

.github/workflows/deploy.yml, docker-compose.yml
> #90 
1. ci/cd 스크립트 수정. 이제 배포하면 docker-compose를 재시작하지 않고, springboot 컨테이너만 재시작
2. 모니터링 구축
=> [Fix/90] docker-compose 수정

.github/workflows/deploy.yml, src/main/java/com/vincent/domain/building/entity/Space.java, src/main/java/com/vincent/domain/socket/entity/Socket.java
=> [Hotfix/94] 층 정보 조회 api 수정

.github/workflows/deploy.yml, src/main/java/com/vincent/domain/building/entity/Space.java, src/main/java/com/vincent/domain/socket/entity/Socket.java
Reverts VINCENT-COMPANY/Vincent-Server#95
=> Revert "[Hotfix/94] 층 정보 조회 api 수정"

src/main/java/com/vincent/domain/bookmark/controller/BookmarkController.java, src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java, src/main/java/com/vincent/domain/bookmark/service/data/BookmarkDataService.java, src/test/java/com/vincent/domain/bookmark/controller/BookmarkControllerTest.java, src/test/java/com/vincent/domain/bookmark/service/BookmarkServiceTest.java, src/test/java/com/vincent/domain/bookmark/service/data/BookmarkDataServiceTest.java
> #92
1. 테스트 코드 수정
2. BookmarkService를 data와 서비스 코드로 분리
오래 걸려서 죄송합니다...
=> [Refactor/92] BookmarkService 리팩토링

src/main/java/com/vincent/domain/building/service/BuildingService.java, src/main/java/com/vincent/domain/building/service/data/FloorDataService.java, src/main/java/com/vincent/domain/building/service/data/SpaceDataService.java, src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java, src/test/java/com/vincent/domain/building/service/data/BuildingDataServiceTest.java, src/test/java/com/vincent/domain/building/service/data/FloorDataServiceTest.java, src/test/java/com/vincent/domain/building/service/data/SpaceDataServiceTest.java
> #99
1. BuildingService를 BuildingDataService와 BuildingService로 분리
- BuildingDataService에서 Repository에 접근
- BuildingService에서 비지니스 로직 처리
2. 테스트 코드 작성
=> :recycle: BuildingService 리팩토링

src/main/java/com/vincent/domain/building/repository/FloorRepository.java, src/main/java/com/vincent/domain/building/service/data/FloorDataService.java, src/main/java/com/vincent/domain/building/service/data/SpaceDataService.java, src/main/java/com/vincent/domain/feedback/service/FeedbackService.java, src/main/java/com/vincent/domain/feedback/service/data/FeedbackDataService.java, src/main/java/com/vincent/domain/socket/service/SocketService.java, src/test/java/com/vincent/domain/building/service/data/BuildingDataServiceTest.java, src/test/java/com/vincent/domain/building/service/data/FloorDataServiceTest.java, src/test/java/com/vincent/domain/building/service/data/SpaceDataServiceTest.java, src/test/java/com/vincent/domain/feedback/service/FeedbackServiceTest.java, src/test/java/com/vincent/domain/feedback/service/data/FeedbackDataServiceTest.java, src/test/java/com/vincent/domain/socket/service/SocketServiceTest.java, src/test/java/com/vincent/domain/socket/service/data/SocketDataServiceTest.java
> #102
1. DataService랑 Service 분리 작업
2. 테스트 코드 작성 및 수정
=> :recycle: Socket, Feedback 서비스 리팩토링

src/main/java/com/vincent/domain/building/controller/BuildingController.java, src/main/java/com/vincent/domain/building/entity/Space.java, src/main/java/com/vincent/domain/building/service/BuildingService.java, src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java, src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
> #105 
> 
1. 공간엔티티의 이미지 필드 제거
2. 공간 등록 api의 이미지 파라미터 제거
=> Hotfix/105 공간 엔티티 이미지 필드 제거

.gitignore, src/main/java/com/vincent/logs/LogConfig.java, src/main/java/com/vincent/logs/LogProcessor.java, src/main/java/com/vincent/logs/LogScheduler.java, src/main/java/com/vincent/logs/LogService.java, src/main/java/com/vincent/logs/entity/DailyActiveUsers.java, src/main/java/com/vincent/logs/entity/MonthlyActiveUsers.java, src/main/java/com/vincent/logs/repository/DailyActiveUsersRepository.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/logback.xml
> #108
1. 자정이 되면 자동으로 로그를 수집해서 DAU를 계산 및 S3에 로그 파일을 업로드가 되게 만들었습니다.
=> :hammer: 로그 수집 api 수정

src/main/java/com/vincent/domain/building/controller/BuildingController.java, src/main/java/com/vincent/domain/building/entity/Space.java, src/main/java/com/vincent/domain/building/service/BuildingService.java, src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java, src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
> #105 
1. 공간 엔티티의 이미지 필드 제거
2. 공간 등록 api의 이미지파라미터 제거
3. 공간 등록 api의 테스트코드에서 이미지 파라미터 제거
=> Fix/105 공간 엔티티의 이미지 필드 제거

src/main/java/com/vincent/domain/feedback/controller/FeedbackController.java, src/main/java/com/vincent/domain/feedback/entity/Feedback.java
> #119 
> 피드백 생성시간 추가, 스웨거 contents 파라미터 중복 제거
=> [Fix/119] :hammer: 피드백 생성 api 오류 

.github/workflows/deploy.yml, docker-compose.yml, src/main/java/com/vincent/config/swagger/SwaggerConfig.java
> #125 
1. 도커 이미지 태그가 올바르지 않아서 제대로 배포가 되지 않고 있었습니다.
=> :hammer: 파이프라인 수정

.github/workflows/deploy.yml
> #139
1. docker-compose.yml 파일이 서버에 복사될 수 있게 action 스크립트 수정
=> :hammer: docker-compose 파일 서버에 복사

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, docker-compose.dev.yml, docker-compose.prod.yml
> #147
운영 서버 배포랑 개발 서버 배포가 하나의 스크립트에 작성되어 있었습니다. 나중에 가면 헷갈릴 수 있어서 2개의 파일로 분리시켰습니다.
=> :hammer: git action script 분리

docker-compose.dev.yml, docker-compose.prod.yml
=> :hammer: docker-compose 수정

src/main/java/com/vincent/config/security/provider/JwtProvider.java, src/main/java/com/vincent/domain/member/controller/MemberController.java, src/main/java/com/vincent/domain/member/controller/dto/MemberRequestDto.java, src/main/java/com/vincent/domain/member/entity/Member.java, src/main/java/com/vincent/domain/member/entity/enums/SocialType.java, src/main/java/com/vincent/domain/member/repository/MemberRepository.java, src/main/java/com/vincent/domain/member/service/MemberService.java, src/main/java/com/vincent/domain/member/service/data/MemberDataService.java, src/test/java/com/vincent/domain/member/controller/MemberControllerTest.java, src/test/java/com/vincent/domain/member/service/MemberServiceTest.java, src/test/java/com/vincent/domain/member/service/data/MemberDataServiceTest.java
> #156
1. SocialType 추가 -> KAKAO, APPLE
2. 사용자를 이메일 + SocialType으로 조회
3. 테스트 코드 수정
4. JWT 토큰 생성할 때 SocialType 추가
=> :sparkles: 애플 로그인 추가

.github/workflows/deploy-dev.yml, src/main/java/com/vincent/config/swagger/SwaggerConfig.java
> #162
1. .env 파일 내용이 덮어쓰여지고 있던 오류 수정
2. swagger에서 현재 로그인이 안되고 있음. 근데 Postman으로 하면 로그인이 잘되고 있습니다.
=> :hammer: git action .env 수정

src/main/java/com/vincent/logging/LoggingFilter.java, src/main/java/com/vincent/logs/DatabaseAppender.java, src/main/java/com/vincent/logs/LogScheduler.java, src/main/java/com/vincent/logs/LogService.java, src/main/java/com/vincent/logs/entity/ApiLogs.java, src/main/java/com/vincent/logs/repository/ApiLogsRepository.java, src/main/resources/application.yml, src/main/resources/logback.xml, src/test/java/com/vincent/domain/member/controller/MemberControllerTest.java
> #167
1. 사용자 요청에 대한 로그를 파일이 아닌 데이터베이스에 기록
2. DAU 계산 로직 수정
=> [Fix/167] :hammer: 로그 작성 DB로 이전

src/test/java/com/vincent/domain/feedback/TestFeedbackRepository.java, src/test/java/com/vincent/domain/feedback/service/FeedbackServiceTest.java, src/test/java/com/vincent/domain/feedback/service/data/FeedbackDataServiceTest.java
=> :recycle: 피드백 테스트 코드 모킹 제거

src/main/java/com/vincent/logs/LogProcessor.java, src/main/java/com/vincent/logs/LogScheduler.java, src/main/java/com/vincent/logs/LogService.java, src/main/java/com/vincent/logs/repository/MonthlyActiveUsersRepository.java
=> :sparkles: MAU 로직 구현

src/main/java/com/vincent/domain/building/service/data/BuildingDataService.java, src/test/java/com/vincent/domain/building/service/data/BuildingDataServiceTest.java
=> [Fix/196] 주변 건물 조회 범위 변수 재확대

src/main/java/com/vincent/domain/iot/controller/IotController.java, src/main/java/com/vincent/domain/iot/controller/converter/IotConverter.java, src/main/java/com/vincent/domain/iot/controller/dto/IotRequestDto.java, src/main/java/com/vincent/domain/iot/entity/Iot.java, src/main/java/com/vincent/domain/iot/repository/IotRepository.java, src/main/java/com/vincent/domain/iot/service/IotService.java, src/main/java/com/vincent/domain/iot/service/data/IotDataService.java, src/main/java/com/vincent/domain/socket/repository/SocketRepository.java, src/main/java/com/vincent/domain/socket/service/data/SocketDataService.java, src/test/java/com/vincent/domain/iot/TestIotRepository.java, src/test/java/com/vincent/domain/iot/service/IotServiceTest.java, src/test/java/com/vincent/domain/iot/service/data/IotDataServiceTest.java, src/test/java/com/vincent/domain/socket/TestSocketRepository.java, src/test/java/com/vincent/domain/socket/service/data/SocketDataServiceTest.java
> #192
1. Iot 장치 등록 API 작성. Iot 장치는 콘센트의 식별 번호로 등록할 수 있게 만들었습니다.
2. 테스트 코드 작성
=> [Feat] Iot 장치 등록

src/main/java/com/vincent/config/redis/RedisConfig.java, src/main/java/com/vincent/config/redis/service/RedisKeyExpirationListener.java, src/main/java/com/vincent/config/redis/service/RedisService.java, src/main/java/com/vincent/domain/iot/controller/IotController.java, src/main/java/com/vincent/domain/iot/controller/converter/IotConverter.java, src/main/java/com/vincent/domain/iot/controller/dto/IotResponseDto.java, src/main/java/com/vincent/domain/iot/entity/Iot.java, src/main/java/com/vincent/domain/iot/service/IotService.java, src/main/java/com/vincent/domain/socket/entity/Socket.java, src/test/java/com/vincent/config/redis/service/TestRedisTemplate.java, src/test/java/com/vincent/domain/iot/TestIotRepository.java, src/test/java/com/vincent/domain/iot/service/IotServiceTest.java
> #206
> 자세한 내용은 노션에 적었습니다.
1. Redis에 소켓의 상태를 저장
2. TTL이 만료되면 서버에 알려서 소켓의 상태를 업데이트
=> [Fix] 소켓 상태 변경 로직 수정
